# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=42)),
                ('nom', models.CharField(max_length=42)),
                ('adresse', models.CharField(max_length=42)),
                ('mail', models.CharField(max_length=42)),
                ('tel', models.CharField(max_length=42)),
                ('marque', models.CharField(max_length=42)),
                ('couleur', models.CharField(max_length=42)),
                ('etat', models.CharField(max_length=42)),
                ('prix', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
            ],
        ),
    ]
