# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170515_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='article',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tel',
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
